// @(#) 1.5 com/src/samples/grafpart/iodgpoin.idl, odgrafpart, od96os2, odos29712d 2/7/97 17:42:00 [3/21/97 17:47:49]
//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odgrafpart
//#
//#   CLASSES: none
//#
//#   ORIGINS: 27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================

#ifndef _GRAFPART_CONTENT_POIN_
#define _GRAFPART_CONTENT_POIN_

// support OD types
#ifndef _ODTYPESB_
#include <ODTypesB.idl>
#endif  // _ODTYPESB_

// subclass from ContentGrafPartFigr
#ifndef _GRAFPART_CONTENT_FIGR_
#include <iodgfigr.idl>
#endif  // _GRAFPART_CONTENT_FIGR_


//==============================================================================
// Classes defined in this interface
//==============================================================================

interface   ContentGrafPartPoin;


//==============================================================================
// Classes used in this interface
//==============================================================================

interface   ContentGrafPartFigr;


//==============================================================================
// ContentGrafPartPoin
//==============================================================================

interface ContentGrafPartPoin :  ContentGrafPartFigr
{

#ifdef __SOMIDL__

    implementation
    {
        functionprefix = ContentGrafPartPoin;

        override:
            somInit,
            MoveBy,
            Resize,
            AdjustBoundingRect,
            ContainsPoint,
            Draw;

        majorversion = 1;
        minorversion = 2;

        passthru C_xih =
            "#define VARIABLE_MACROS"
            "#define METHOD_MACROS" ;

#if defined(__PRIVATE__) && defined (_PLATFORM_OS2_)
        POINTL pPt1;       // long point buffers for OS/2 Gpi calls
#endif  // __PRIVATE__  && _PLATFORM_OS2_

    };

#endif  // __SOMIDL__
};


#endif  // _GRAFPART_CONTENT_POIN_

// end of file  *****************************************************
