// @(#) 1.2 com/src/samples/grafpart/iodgtext.idl, odgrafpart, od96os2, odos29712d 2/7/97 17:42:25 [3/21/97 17:49:30]
//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odgrafpart
//#
//#   CLASSES: none
//#
//#   ORIGINS: 27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================

#ifndef _GRAFPART_CONTENT_TEXT_
#define _GRAFPART_CONTENT_TEXT_

// support OD types
#include <ODTypesB.idl>

// subclass from ContentGrafPartRect
#include <iodgrect.idl>


//==============================================================================
// Classes defined in this interface
//==============================================================================

interface   ContentGrafPartLine;

//==============================================================================
// Classes used in this interface
//==============================================================================

interface   ContentGrafPartFigr;
interface   ContentGrafPartRect;


//==============================================================================
// ContentGrafPartLine
//==============================================================================

interface ContentGrafPartText :  ContentGrafPartRect
{

#ifdef __PRIVATE__
    attribute   string fFontName ;
    attribute   long   fFontHeight ;
    attribute   long   fFontAngle ;
    attribute   long   fFontFlags ;
    attribute   string fText ;
#endif  // __PRIVATE__

#ifdef __SOMIDL__

    implementation
    {
        functionprefix = ContentGrafPartText;

        fFontName   : noset ;
        fText       : noset ;

        override:
            somInit,
            somUninit,
            WriteContents,
            ReadContents,
            DeleteContents,
            Draw;

        releaseorder:
            _set_fText       ,
            _get_fText       ,
            _set_fFontHeight ,
            _get_fFontHeight ,
            _set_fFontAngle  ,
            _get_fFontAngle  ,
            _set_fFontName   ,
            _get_fFontName   ,
            _set_fFontFlags  ,
            _get_fFontFlags   ;

        majorversion = 1;
        minorversion = 2;

        passthru C_xih =
            "#define VARIABLE_MACROS"
            "#define METHOD_MACROS" ;

#if defined(__PRIVATE__) && defined (_PLATFORM_OS2_)
        POINTL pPt1, pPt2;     // long point buffers for OS/2 Gpi calls
#endif  // __PRIVATE__  && _PLATFORM_OS2_

    };

#endif  // __SOMIDL__
};


#endif  // _GRAFPART_CONTENT_TEXT_

// end of file  *****************************************************
