$ ====START_GENERATED_PROLOG======================================
$ 
$ 
$    COMPONENT_NAME: odsimplepart
$ 
$    CLASSES: none
$ 
$    ORIGINS: 82,27
$ 
$ 
$    (C) COPYRIGHT International Business Machines Corp. 1995,1996
$    All Rights Reserved
$    Licensed Materials - Property of IBM
$    US Government Users Restricted Rights - Use, duplication or
$    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$    	
$    IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
$    ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
$    PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
$    CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
$    USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
$    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
$    OR PERFORMANCE OF THIS SOFTWARE.
$ 
$ ====END_GENERATED_PROLOG========================================
$ 
$ @(#) 1.4 com/src/samples/simple/en_US/iodsmple.msg, odsimplepart, od96os2, odos29712d 1/29/97 17:36:26 [3/21/97 17:49:37]

$ 
$
$ /********************************************************************/
$ /*  Licensed Materials - Property of IBM                            */
$ /*                                                                  */
$ /*                                                                  */
$ /* Copyright (C) International Business Machines Corp., 1996.       */
$ /*                                                                  */
$ /*  US Government Users Restricted Rights -                         */
$ /*  Use, duplication, or disclosure restricted                      */
$ /*  by GSA ADP Schedule Contract with IBM Corp.                     */
$ /*                                                                  */
$ /********************************************************************/
$
$ This is the message file for Simple Part on NT, Win95 and OS/2.
$

$ -------------------------------------------------------------
$ Simple Part Messages in ENGLISH
$ -------------------------------------------------------------
$quote "

$set SP_MSG_SET

$ -------------------------------------------------------------
$ Message 1: Simple Part Help Menu Item
$
$ When the user selects the "Simple part help" item of 
$ the HELP menu, information on how to use the Simple Part
$ is displayed.
$ -------------------------------------------------------------

SPMSG_HELPMENU       "Simple part help"


$ -------------------------------------------------------------
$ Message 2: Simple Part Information Menu Item
$
$ The user may select the "Simple part information" item of      
$ the HELP menu to find out the version of the Simple part 
$ installed and its copyrights.
$ -------------------------------------------------------------

SPMSG_INFOMENU       "Simple part information"

$ -------------------------------------------------------------
$ Message 3: Simple Part Information Message Box Title
$
$ This is the title of the message box which shows
$ version and copyright information for the Simple part.
$ The message box is displayed after the user selects
$ the "Simple part information" menu item of the HELP menu.
$ -------------------------------------------------------------

SPMSG_INFOTITLE       "Simple Part Information"

$ -------------------------------------------------------------
$ Message 4: Simple Part Version and Copyright Information 
$            for the Information Message Box
$       
$ This message contains the Simple part's version number and the
$ legal rights that IBM has over the Simple part. This message
$ is shown in the message box that appears when the user
$ selects the "Simple part information" item of the HELP menu.
$ -------------------------------------------------------------

SPMSG_INFO        "Simple Part Version 1.0 \n\
Copyright International Business Machines Corporation 1996,1997. \
All rights reserved."
