//#====START_GENERATED_PROLOG======================================
//#
//#
//#   COMPONENT_NAME: odshapepart
//#
//#   CLASSES: none
//#
//#   ORIGINS: 82,27
//#
//#
//#   (C) COPYRIGHT International Business Machines Corp. 1995,1996
//#   All Rights Reserved
//#   Licensed Materials - Property of IBM
//#   US Government Users Restricted Rights - Use, duplication or
//#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//#   	
//#   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
//#   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//#   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
//#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
//#   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
//#   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
//#   OR PERFORMANCE OF THIS SOFTWARE.
//#
//#====END_GENERATED_PROLOG========================================
//#
/* @(#)Z 1.14 com/src/samples/shape/iodshape.idl, odshapepart, od96os2, odos29712d 97/03/21 17:45:25 (96/11/01 08:53:50) */
#ifdef __PRIVATE__
//#
//#     File:           Shape.idl
//#
//#     Contains:       IDL description of Shape Part
//#
#endif


#ifndef _SHAPE_H_
#define _SHAPE_H_
#ifndef _SIMPLPRT_

#include "iodsimpl.idl"
#endif

interface M_ShapePart;
interface ODFrame;

typedef somToken COLORREF;


interface ShapePart : SimplePart
{

        void HandleColorChange(in ODFrame frame);
        void InvalidateAllFrames();

#ifdef __SOMIDL__
        implementation
        {
                functionprefix = ShapePart;
                metaclass     = M_ShapePart;
                majorversion = 1;
                minorversion = 0;
                dllname = "iodshape.dll";

        releaseorder:
               HandleColorChange,
               InvalidateAllFrames;

        override:
               somInit,
               somUninit,
               CommonInit,
               InitPart,
               InitPartFromStorage,
               CloneInto,
               Externalize,
               AdjustViewTypeShapes,
               CreateIcons,
               HandleMenuEvent,
               DrawFrame,
               AdjustMenus,
               UndoAction,
               RedoAction,
               Release;

        passthru C_xh = ""
         ;
        passthru C_xh_after = ""
         ;
        passthru C_xih = ""
         ;

        // instance variables
         ODSession           fSession;
         ODPart              fPartWrapper;
         COLORREF            fBackgroundColor;
         ODBoolean           fDraftReadOnly;
        };
#endif
};

interface M_ShapePart : M_SimplePart
{

#ifdef __SOMIDL__
  implementation
  {
    functionprefix = M_ShapePart;
    override:
      clsGetODPartHandlerName,
      clsGetODPartHandlerDisplayName,
      clsGetODPartKinds,
      clsGetOLE2ClassId,
      clsGetWindowsIconFileName;
  };
#endif
};
#endif  // _SHAPE_H_


