$ ====START_GENERATED_PROLOG======================================
$
$
$    COMPONENT_NAME: odshapepart
$
$    CLASSES: none
$
$    ORIGINS: 82,27
$
$
$    (C) COPYRIGHT International Business Machines Corp. 1995,1996
$    All Rights Reserved
$    Licensed Materials - Property of IBM
$    US Government Users Restricted Rights - Use, duplication or
$    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$    	
$    IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
$    ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
$    PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
$    CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
$    USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
$    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
$    OR PERFORMANCE OF THIS SOFTWARE.
$
$ ====END_GENERATED_PROLOG========================================
$
$ @(#) 1.4 com/src/samples/shape/en_US/iodshpe.msg, odshapepart, od96os2, odos29712d 2/12/97 15:55:32 [3/21/97 17:50:09]

$
$
$ This is the message file for Shape Part on NT, Win95 and OS/2.
$


$ -------------------------------------------------------------
$ Shape Part Messages in ENGLISH
$ -------------------------------------------------------------
$quote "

$set SHAPE_MSG_SET

$ -------------------------------------------------------------
$ Message 1: Shape Part Background Color Menu
$
$ The user may change the color of the Shape Part by
$ selecting the "Background color" item of the EDIT menu.
$ When the user selects this item a system color dialog
$ is displayed from which the user may select a new color.
$ -------------------------------------------------------------

SHAPEMSG_COLORMENU       "Background color..."

$ -------------------------------------------------------------
$ Message 2: Shape Part Help Menu Item
$
$ When the user selects the "Shape Part help" item of
$ the HELP menu, information on how to use the Shape Part
$ is displayed.
$ -------------------------------------------------------------

SHAPEMSG_HELPMENU       "Shape Part help"


$ -------------------------------------------------------------
$ Message 3: Shape Part Information Menu Item
$
$ The user may select the "Shape Part information" item of
$ the HELP menu to find out the version of the Shape Part
$ installed and its copyrights.
$ -------------------------------------------------------------

SHAPEMSG_INFOMENU       "Shape Part information"

$ -------------------------------------------------------------
$ Message 4: Shape Part Information Message Box Title
$
$ This is the title of the message box which shows
$ version and copyright information for the Shape Part.
$ The message box is displayed after the user selects
$ the "Shape Part information" menu item of the HELP menu.
$ -------------------------------------------------------------

SHAPEMSG_INFOTITLE       "Shape Part Information"

$ -------------------------------------------------------------
$ Message 5: Shape Part Version and Copyright Information
$            for the Information Message Box
$
$ This message contains the Shape Part's version number and the
$ legal rights that IBM has over the Shape Part. This message
$ is shown in the message box that appears when the user
$ selects the "Shape Part information" item of the HELP menu.
$ -------------------------------------------------------------

SHAPEMSG_INFO        "Shape Part Version 1.0 \n\
Copyright International Business Machines Corporation 1996,1997. \
All rights reserved."
