/*====START_GENERATED_PROLOG======================================
 */
/*
 *   COMPONENT_NAME: oddynamicpart
 *
 *   CLASSES: none
 *
 *   ORIGINS: 82,27
 *
 *
 *   (C) COPYRIGHT International Business Machines Corp. 1995,1996
 *   All Rights Reserved
 *   Licensed Materials - Property of IBM
 *   US Government Users Restricted Rights - Use, duplication or
 *   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *   	
 *   IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
 *   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *   PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
 *   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
 *   USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 *   OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
 *   OR PERFORMANCE OF THIS SOFTWARE.
 */
/*====END_GENERATED_PROLOG========================================
 */
/* @(#) 1.3 com/src/samples/dynamicp/bmenu/bmenures.h, oddynamicpart, od96os2, odos29712d 97/03/21 17:44:47 (97/02/14 11:51:27) */
/* resource IDs used by menu handling */

/* resource IDs for menu commands */
#define DYNAMICPART_MENU_BASE MENUID_ACTIVEPART_USER+100
#define DYNAMICPART_MENU                  DYNAMICPART_MENU_BASE

#define DYNAMICPART_MENU_ROTATE           DYNAMICPART_MENU+1
#define DYNAMICPART_MENU_RDIR             DYNAMICPART_MENU+2
#define DYNAMICPART_MENU_RDIR_FORWARD     DYNAMICPART_MENU+3
#define DYNAMICPART_MENU_RDIR_BACKWARD    DYNAMICPART_MENU+4

#define DYNAMICPART_MENU_STOPPED          DYNAMICPART_MENU+6
#define DYNAMICPART_MENU_RESUMED          DYNAMICPART_MENU+7

#define DYNAMICPART_MENU_HSHEAR           DYNAMICPART_MENU+10
#define DYNAMICPART_MENU_HDIR             DYNAMICPART_MENU+11
#define DYNAMICPART_MENU_HDIR_FORWARD     DYNAMICPART_MENU+12
#define DYNAMICPART_MENU_HDIR_BACKWARD    DYNAMICPART_MENU+13
#define DYNAMICPART_MENU_HSTOPPED         DYNAMICPART_MENU+14

#define DYNAMICPART_MENU_VSHEAR           DYNAMICPART_MENU+17
#define DYNAMICPART_MENU_VDIR             DYNAMICPART_MENU+18
#define DYNAMICPART_MENU_VDIR_FORWARD     DYNAMICPART_MENU+19
#define DYNAMICPART_MENU_VDIR_BACKWARD    DYNAMICPART_MENU+20
#define DYNAMICPART_MENU_VSTOPPED         DYNAMICPART_MENU+21

#define DYNAMICPART_MENU_RESET            DYNAMICPART_MENU+24

/* String resources */
#define DYNAMICPART_MENU_ERROR            DYNAMICPART_MENU+30
#define DYNAMICPART_MENU_ROTATION_STARTED DYNAMICPART_MENU+31
#define DYNAMICPART_MENU_ROTATION_STOPPED DYNAMICPART_MENU+32
#define DYNAMICPART_MENU_HSHEAR_STARTED   DYNAMICPART_MENU+33
#define DYNAMICPART_MENU_HSHEAR_STOPPED   DYNAMICPART_MENU+34
#define DYNAMICPART_MENU_VSHEAR_STARTED   DYNAMICPART_MENU+35
#define DYNAMICPART_MENU_VSHEAR_STOPPED   DYNAMICPART_MENU+36

