$ @(#)Z 1.1 com/src/samples/text/ja_JP/iodtextm.msg, odtextpart, od96os2, odos29712d 97/03/21 17:50:07 (97/02/11 09:25:38)


$ ====START_GENERATED_PROLOG======================================
$
$
$    COMPONENT_NAME: odtextpart
$
$    CLASSES: none
$
$    ORIGINS: 27
$
$
$    (C) COPYRIGHT International Business Machines Corp. 1995,1996
$    All Rights Reserved
$    Licensed Materials - Property of IBM
$    US Government Users Restricted Rights - Use, duplication or
$    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$    IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
$    ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
$    PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
$    CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
$    USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
$    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
$    OR PERFORMANCE OF THIS SOFTWARE.
$
$ ====END_GENERATED_PROLOG========================================
$


$ -------------------------------------------------------------
$ Text Part Messages in ENGLISH
$ -------------------------------------------------------------
$quote "

$set TP_MSG_SET

$ -------------------------------------------------------------
$ Messages 1-2: Import/Export menu items on Options menu
$
$       The Import option allows ASCII text files to be opened
$       into the OpenDoc Text Part Handler.  The Export option
$       allows the text in the Text Part to be saved to an
$       ASCII text file.
$ -------------------------------------------------------------

TP_MSG_IMPORT_MENU       "Import"
TP_MSG_EXPORT_MENU       "Export"

$ -------------------------------------------------------------
$ Messages 3-4: Import/Export dialog titles
$
$       The Import and Export Dialog Boxes need title strings,
$       because the system defaults are "Open" and "Save As".
$ -------------------------------------------------------------

TP_MSG_IMPORT_DLG        "Import"
TP_MSG_EXPORT_DLG        "Export"

$ -------------------------------------------------------------
$ Message 5: File Filter to use with dialogs
$
$       The Import and Export Dialog Boxes use file filters to
$       determine which files to allow the user to select from.
$ -------------------------------------------------------------

TP_MSG_DLG_FILTER   "All (*.*)\0*.*\0\0"


