$ @(#) 1.1 com/src/samples/grafpart/ja_JP/iodgraph.msg, odgrafpart, od96os2, odos29712d 2/11/97 09:20:46 [3/21/97 17:47:41]
$ ====START_GENERATED_PROLOG======================================
$
$
$    COMPONENT_NAME: odgrafpart
$
$    CLASSES: none
$
$    ORIGINS: 27
$
$
$    (C) COPYRIGHT International Business Machines Corp. 1995,1996
$    All Rights Reserved
$    Licensed Materials - Property of IBM
$    US Government Users Restricted Rights - Use, duplication or
$    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$    	
$    IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
$    ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
$    PURPOSE. IN NO EVENT SHALL IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
$    CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
$    USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
$    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
$    OR PERFORMANCE OF THIS SOFTWARE.
$
$ ====END_GENERATED_PROLOG========================================
$
$ Message file for GrafPart Sample KAC 9608
$   This is the message file for GrafPart on NT, Win95 and OS/2.

$ -------------------------------------------------------------
$ Graphics Part (GrafPart) Messages in ENGLISH for US
$ -------------------------------------------------------------

$quote "

$set GP_MSG_SET_ONE

GP_MSG_DASH         "--------"
GP_MSG_ADD          "Add mode"
GP_MSG_SELECT       "Select mode"
GP_MSG_EDIT         "Edit mode"
GP_MSG_REFRESH      "Refresh Screen"
GP_MSG_MB_WARNING   "Don't know how to handle this menu choice:   %d   !\n"
GP_MSG_ADD_POIN     "Point"
GP_MSG_ADD_LINE     "Line"
GP_MSG_ADD_RECT     "Rectangle"
GP_MSG_ADD_ELLI     "Ellipse"
GP_MSG_ADD_CIRC     "Circle"
GP_MSG_ADD_PLIN     "Polyline"
GP_MSG_ADD_PGON     "Polygon"
GP_MSG_ADD_FREE     "Freehand"
GP_MSG_ADD_TEXT     "Text"
GP_MSG_ADD_IMAG     "Image"

$ -------------------------------------------------------------
$ end of file
$ -------------------------------------------------------------
